title: Aarushi Gupta                          # the main title
logo: /assets/img/Photo_Aarushi.jpeg

tagline: Data Analysis, Data Science, Machine Learning, Artificial Intelligence  # it will display as the sub-title

description:                        
    I am an aspiring data scientist eager to leverage machine learning and data manipulation techniques to extract meaningful insights, make informed decisions, and solve challenging real-life problems.



social:
  
  links:
    - https://www.linkedin.com/in/aarushi-gupta-63494b21b/      
    - https://github.com/Aarushi17Gupta      


theme: jekyll-theme-minimal
