title: Aarushi Gupta
logo: /assets/img/Photo_Aarushi.jpeg

description:
  <p align="center">

  <br> 
  I am an aspiring data scientist working eager to leverage machine learning and data manipulation techniques to extract meaningful insights, make informed decisions, and solve challenging real-life problems.
  </br>
  </p>


theme: jekyll-theme-minimal
