title: Aarushi Gupta
logo: /assets/img/Photo_Aarushi.jpeg

description:
  <p align="center">
  <a href="/assets/Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/aarushi-gupta-63494b21b/">LinkedIn</a> |
  <a href="https://github.com/Aarushi17Gupta">GitHub</a>

  <br>   
  I am an aspiring data scientist working on Data Analysis, Machine Learning , NLP and Artificial Intelligence related projects.
  <br>
  </p>

theme: jekyll-theme-minimal
