title: <p align="center"> Aarushi Gupta </p>
logo: /assets/img/Photo_Aarushi.jpeg
description: I am an aspiring data scientist eager to leverage machine learning and data manipulation techniques to extract meaningful insights, make informed decisions, and solve challenging real-life problems.
show_downloads: false
#google_analytics:
color-scheme: auto
theme: jekyll-theme-minimal
