title: <p align="center"> Aarushi Gupta </p>
logo: /assets/img/Photo_Aarushi.jpeg
description: I am an aspiring data scientist eager to leverage machine learning and data manipulation techniques to extract meaningful insights, make informed decisions, and solve challenging real-life problems.
show_downloads: false
#google_analytics:
color-scheme: auto
sidebar:
  - name: Google Scholar
    icon: fa-solid fa-user-graduate
    link: https://scholar.google.com/citations?user=zR6afi8AAAAJ
  - name: GitHub
    icon: fa-brands fa-github
    link: https://github.com/Aarushi17Gupta
  - name: Linkedln
    icon: fa-brands fa-linkedln
    link: https://www.linkedin.com/in/aarushi-gupta-63494b21b/
  - name: Blog
    icon: fa-solid fa-pen
    #link:

theme: jekyll-theme-minimal
